name: AstraDev | Database Admin

on:
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]
  workflow_dispatch:

jobs:
  BUILD:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 11
          cache: 'maven'
      - name: Build with Maven
        run: |
          mvn install -Dmaven.test.skip=true
  AWS_US_WEST2_CORE:
    needs: BUILD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 11
          cache: 'maven'
      - name: Maven Test
        env:
          ASTRA_DB_APPLICATION_TOKEN_DEV: ${{ secrets.ASTRA_DB_APPLICATION_TOKEN_DEV }}
          ASTRA_CLOUD_PROVIDER_DEV: AWS
          ASTRA_CLOUD_REGION_DEV: us-west-2
        run: |
          cd astra-db-java
          mvn test -Dtest=com.datastax.astra.test.integration.dev.AstraDevDatabaseAdminITTest

  GCP_EUROPE_WEST4:
    needs: BUILD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 11
          cache: 'maven'
      - name: Run test for DEV
        env:
          ASTRA_DB_APPLICATION_TOKEN_DEV: ${{ secrets.ASTRA_DB_APPLICATION_TOKEN_DEV }}
          ASTRA_CLOUD_PROVIDER_DEV: GCP
          ASTRA_CLOUD_REGION_DEV: europe-west4
        run: |
          cd astra-db-java
          mvn test -Dtest=com.datastax.astra.test.integration.dev.AstraDevDatabaseAdminITTest

  GCP_US_CENTRAL1:
    needs: BUILD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 11
          cache: 'maven'

      - name: Run test for DEV
        env:
          ASTRA_DB_APPLICATION_TOKEN_DEV: ${{ secrets.ASTRA_DB_APPLICATION_TOKEN_DEV }}
          ASTRA_CLOUD_PROVIDER_DEV: GCP
          ASTRA_CLOUD_REGION_DEV: us-central1
        run: |
          cd astra-db-java
          mvn test -Dtest=com.datastax.astra.test.integration.dev.AstraDevDatabaseAdminITTest
